# Generated by Django 4.1 on 2023-01-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=32, verbose_name='标题')),
                ('price', models.ImageField(upload_to='', verbose_name='价格')),
                ('pub_date', models.DateTimeField(verbose_name='出版日期')),
            ],
        ),
    ]
