# Generated by Django 4.1 on 2023-01-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(verbose_name='价格'),
        ),
    ]
