# Generated by Django 4.1 on 2023-01-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sers', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(verbose_name='出版日期'),
        ),
    ]
