# Generated by Django 4.1 on 2023-01-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sers', '0003_alter_book_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(verbose_name='出版日期'),
        ),
    ]
